### ISSUE TITLE
README

### ISSUE THREAD

**Issue by Kasualix** [DM-Fabric-Ports/KuaYue#1]
[这个](https://github.com/DM-Fabric-Ports/KuaYue/blob/pre-1.18.2-0.0.8-VIVIT/README.md)是不是跟[这个](https://github.com/DM-Fabric-Ports/CreateMorePotatoes/blob/fabric/dev/README.md)搞混了

**Comment by JieningYu** [comment]
<img width="933" alt="image" src="https://user-images.githubusercontent.com/61787533/204678961-d88563b2-58e6-40d7-ba4a-61aa2af3e00d.png">
没搞混吧（
